# Generated by Django 4.0.10 on 2023-05-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateController', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='grade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='a', max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='surname',
            field=models.CharField(default='a', max_length=255),
        ),
    ]
