# Generated by Django 4.0.10 on 2023-05-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateController', '0002_candidate_grade_candidate_name_candidate_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
