# Generated by Django 4.0.10 on 2023-06-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateController', '0003_candidate_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
