# Generated by Django 4.0.10 on 2023-06-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateController', '0004_candidate_is_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
