# Generated by Django 4.0.10 on 2023-06-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateController', '0005_candidate_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='grade',
            field=models.FloatField(default=0.0),
        ),
    ]
