# Generated by Django 4.0.10 on 2023-06-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidateController', '0006_alter_candidate_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='is_rejected',
        ),
    ]
