# Generated by Django 4.0.10 on 2023-06-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateController', '0007_remove_candidate_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='has_most_counts',
            field=models.BooleanField(default=False),
        ),
    ]
