# Generated by Django 4.0.10 on 2023-06-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateController', '0008_candidate_has_most_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
