# Generated by Django 4.0.10 on 2023-06-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateController', '0009_candidate_is_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='id',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='student_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
