# Generated by Django 4.0.10 on 2023-06-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidateController', '0010_remove_candidate_id_alter_candidate_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='faculty',
        ),
    ]
