# Generated by Django 4.0.10 on 2023-05-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_number', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('auth_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
