# Generated by Django 4.0.10 on 2023-06-07 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidateController', '0010_remove_candidate_id_alter_candidate_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='pdfs/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidateController.candidate')),
            ],
        ),
    ]
