# Generated by Django 4.0.10 on 2023-06-07 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extraUserController', '0004_user_email'),
        ('documentController', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extraUserController.user'),
        ),
    ]
