# Generated by Django 4.0.10 on 2023-06-07 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidateController', '0010_remove_candidate_id_alter_candidate_student_id'),
        ('documentController', '0002_alter_pdf_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidateController.candidate'),
        ),
    ]
