# Generated by Django 4.0.10 on 2023-06-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentController', '0003_alter_pdf_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='name',
        ),
    ]
