# Generated by Django 4.0.10 on 2023-06-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('studentNumber', models.CharField(max_length=20, unique=True)),
                ('hasVoted', models.BooleanField(default=False)),
                ('hasApplied', models.BooleanField(default=False)),
                ('electionStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
