# Generated by Django 4.0.10 on 2023-06-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraUserController', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='studentNumber',
            field=models.CharField(max_length=20),
        ),
    ]
