# Generated by Django 4.0.10 on 2023-06-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraUserController', '0002_alter_user_studentnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.FloatField(default=2.0),
        ),
    ]
