# Generated by Django 4.0.10 on 2023-06-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraUserController', '0003_user_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='a@std.iyte.edu.tr', max_length=254),
        ),
    ]
