# Generated by Django 4.0.10 on 2023-06-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraUserController', '0004_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='Computer Engineering', max_length=255),
        ),
    ]
